export const FETCH_POKEMONS_START = 'FETCH_POKEMONS_START'
export const FETCH_POKEMONS_SUCCESS = 'FETCH_POKEMONS_SUCCESS'
export const FETCH_POKEMONS_FAIL = 'FETCH_POKEMONS_FAIL'

export const FETCH_POKEMON_DETAILS_START = 'FETCH_POKEMON_DETAILS_START'
export const FETCH_POKEMON_DETAILS_SUCCESS = 'FETCH_POKEMON_DETAILS_SUCCESS'
export const FETCH_POKEMON_DETAILS_FAIL = 'FETCH_POKEMON_DETAILS_FAIL'

export const DELETE_POKEMONS = 'DELETE_POKEMONS'
